### PR TITLE
[uconfig_gui] Made the FilePage to remember to the last selected file

### PR DESCRIPTION
**Pull request by martonmiklos**
After opening a file with the FilePage next time the same path will be
opened with the file browse dialog.

This PR also enabling c++11 in the pro file as discussed in the #19

### CODE REVIEW

**Comment by sebcaux** [comment]
Hi, thanks for this PR.
Travis fail because it use Qt5.2 : I want to keep Qt5.2 compatibility for old systems.
Q_ENUM macro appears in Qt5.5, so is it possible to remove this statement ?

**Comment by martonmiklos** [comment]
Yes we can live without this QMetaEnum based solution, just I thought it is going to be more elegant this way. I will get a Qt 5.2 copy for development to prevent these errors.

**Comment by martonmiklos** [comment]
I have enabled C++11 for the GUI project, so it shall be OK now.

**Comment by sebcaux** [comment]
Can you please remove C++ pro option and temporary brew option fix?

**Comment by martonmiklos** [comment]
It should be mergable by now!

**Pull request merged**
